### PR TITLE
PBI-34: View Assignment 

### LINKED ISSUE #89: PBI-34: Teacher & Students can see assignment
**Story Points: 8**

### PR DESCRIPTION
**Pull request by IlmaMannix**

### CODE REVIEW

**Review by kanziebub — APPROVED** [review]
GG gaming

**Review by AldiNFitrah — APPROVED** [review]
LGTM!

**Review by Zsaschz — APPROVED** [review]
IKZZZZ!

**Review by fxdros — APPROVED** [review]
LGTM

**Pull request merged**
