### PR TITLE
[REFACTOR] api call

### PR DESCRIPTION
**Pull request by kanziebub**

### CODE REVIEW

**Review by AldiNFitrah — APPROVED** [review]
lgtm!

**Review by fxdros — APPROVED** [review]

**Review by IlmaMannix — APPROVED** [review]
I see, you're also refactoring variables that the rest of the dev team has created. Thanks for helping them ^^

**Review by AldiNFitrah — APPROVED** [review]
LGTM, thanks!!

**Review by IlmaMannix — COMMENTED** [review]
I c conflict, do not forget to resolve conflict

**Pull request merged**
